name: Build and deploy to GitHub Pages
on:
  push:
    branches:
      - 'main'
jobs:
    # Build job
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3
              with:
                  version: 8

            - name: pnpm install
              run: pnpm install

            - name: pnpm build
              run: pnpm build

            - uses: actions/upload-artifact@v4
              with:
                  name: github-pages
                  path: build/

    # Deploy job
    deploy:
        # Add a dependency to the build job
        needs: build

        # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
        permissions:
            contents: read
            pages: write # to deploy to Pages
            id-token: write # to verify the deployment originates from an appropriate source

        # Deploy to the github-pages environment
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        # Specify runner + deployment step
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
